### ISSUE TITLE
[TASK] BlockTris: add idle mode

### ISSUE THREAD

**Issue by inf0matics** [thespielplatz/tspi-blockclock#3]
The idea is to have an idle mode in the blocktris app which shows the time and the block animation, when a new BTC block is found.

Currently it shows the text `TETRIS` with some blocks falling down

### Todo

- [ ] If no player is connected, show time with HH:MM after some idle time. Idle time can be set in .env
- [ ] Play new block animation, when time is shown and a new block is found. Configurable in .env
- [ ] Automatically turn off idle mode when a new player is connected

### Acceptance Criteria
- new env var to config with prefix `BLOCKTRIS_`
- Default should be no idle mode

@daskleinesys That's the definition AFAI understood it. Please change it, because it's your idea ;)
